02-javascript data types
js-tasks-ru/js-20230117_eqillibrium pull request #2
Opened 2023-01-24 07:02 UTC by eqillibrium

done))

2023-01-24 07:03 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-01-24 09:18 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return result.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2023-01-24 09:19 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    const [key] = e;
`e` не самое удачное имя для переменной

2023-01-24 09:19 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  const result = Object.entries(obj).filter((e) => {
👍 good

2023-01-24 09:20 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  //     delete result[f];
использовать `delete` в связке с объектом не рекомендуется, ведь копирование объекта `{...obj}` делает `shallow copy` или другими словами неглубокую копию, поэтому удаление может привести к весьма неожиданным последствиям

2023-01-24 09:20 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  const result = Object
good 👍

2023-01-24 09:20 UTC, dosandk requested changes
решение `sortStrings` следует поправить

2023-01-24 16:47 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-01-26 12:08 UTC, dosandk approved these changes
good 👍

2023-01-26 12:08 UTC, merged